### ISSUE TITLE
Lambda Error

### ISSUE THREAD

**Issue by SilentDev1** [G-mel/Who-Is-At-The-Door#2]
{
  "errorMessage": "Cannot find module '/var/task/index'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:276:25)",
    "Module.require (module.js:353:17)",
    "require (internal/module.js:12:17)"
  ]
}

Log output
The area below shows the logging calls in your code. These correspond to a single row within the CloudWatch log group corresponding to this Lambda function. Click here to view the CloudWatch log group.
START RequestId: 8e9c1432-bf49-11e6-a238-755f8c722b4f Version: $LATEST
Unable to import module 'index': Error
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
END RequestId: 8e9c1432-bf49-11e6-a238-755f8c722b4f
REPORT RequestId: 8e9c1432-bf49-11e6-a238-755f8c722b4f	Duration: 29.98 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 15 MB

**Comment by G-mel** [comment]
Looks like there is an error on the index.handler in lambda. Make sure that you **zip** the **entire repository** when you upload it to Lambda (via Amazon S3) to include all of the code as well as the node_modules folder to have all of the correct dependencies.

Please let me know if this is the error that you are experiencing. 

Reference: http://stackoverflow.com/questions/37745068/problems-uploading-lambda-function-code-on-amazon-web-services-console

**Comment by SilenceDev** [comment]
I did as the reference, all the files are uploaded. But still get this error

{
  "errorMessage": "Failed to parse service account key file: Error: ENOENT: no such file or directory, open './<PiAI>.json'",
  "errorType": "Error",
  "stackTrace": [
    "new Auth (/var/task/node_modules/firebase/auth-node/auth.js:77:25)",
    "Object.serviceFactory [as auth] (/var/task/node_modules/firebase/auth-node/index.js:17:14)",
    "N.u (/var/task/node_modules/firebase/app-node.js:13:94)",
    "/var/task/node_modules/firebase/auth-node/index.js:34:9",
    "/var/task/node_modules/firebase/app-node.js:14:322",
    "Array.forEach (native)",
    "Object.R.e.initializeApp (/var/task/node_modules/firebase/app-node.js:14:295)",
    "Object.<anonymous> (/var/task/database.js:10:10)",
    "Module._compile (module.js:409:26)"
  ]
}

**Comment by G-mel** [comment]
"errorMessage": "Failed to parse service account key file: Error: ENOENT: no such file or directory

is saying that the firebase npm module cannot find the proper <firebaseSecurityProfile>.json security profile when these lines of code in _firebase.js_ are executed:

`firebase.initializeApp({
  databaseURL: '<firebaseURLhere>',
  serviceAccount: './<firebaseSecurityProfile>.json'
});`

where the databaseURL and serviceAccount parameters have to match with your firebase databaseURL credentials and security profile JSON file.

Reference: https://groups.google.com/forum/#!topic/firebase-talk/nY14ANXQbU0
and http://stackoverflow.com/questions/38320027/firebase-npm-authentication-error

**Comment by SilenceDev** [comment]
Ok so I think I got it working, but now it give me this in Lambda

{
  "errorMessage": "Cannot read property 'application' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "AlexaSkill.execute (/var/task/AlexaSkill.js:83:62)",
    "exports.handler (/var/task/index.js:170:10)"
  ]
}

and on testing its saying, The remote endpoint could not be called, or the response it returned was invalid.

**Comment by G-mel** [comment]
Looks like from line 83 of AlexaSkill.js:

`console.log("session applicationId: " + event.session.application.applicationId);`

the `session` attribute is undefined. Not really sure what's causing it but it would be worth debugging using cloud-watch.

**Comment by SilenceDev** [comment]
I've tried that but cloud-watch just keep saying "There was an error loading Log Streams. Please try again by refreshing this page."

**Comment by G-mel** [comment]
Sorry I've been busy with final exams, did you manage to resolve your issue?

**Comment by SilentDev1** [comment]
not yet

**Comment by G-mel** [comment]
LukeSwart's answer may be of help: https://github.com/garnaat/kappa/issues/5

**Comment by 0btain** [comment]
@G-mel We've been trying to implement your solution but we are still getting the same error. While your answer is nearly 2 years old the person by LukeSwart doesnt exist anymore
Any solutions?
Regards!
